// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type IgnoredObservation struct {
	ObservationID int64
	IgnoredAt     int64
}

type Observation struct {
	ID          int64
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	FirstSeen   int64
}

type Project struct {
	ID        int64
	Name      string
	CreatedAt int64
}

type Rule struct {
	ID               int64
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
	CreatedAt        int64
}

type Tick struct {
	Ts            int64
	ObservationID int64
	ProjectID     sql.NullInt64
}

type WatchedProgram struct {
	ID         int64
	Kind       string
	Identifier string
	CreatedAt  int64
}
