// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Company struct {
	ID          int64
	Name        string
	CreatedAt   int64
	BillingMode string
	Currency    sql.NullString
	RateCents   sql.NullInt64
	BilledFrom  sql.NullString
}

type IgnoredObservation struct {
	ObservationID int64
	IgnoredAt     int64
}

type Invoice struct {
	ID         int64
	CompanyID  int64
	SentAt     int64
	Note       string
	CreatedAt  int64
	Number     sql.NullString
	PdfPath    sql.NullString
	TotalCents sql.NullInt64
	Currency   sql.NullString
	SenderKey  sql.NullString
}

type Observation struct {
	ID          int64
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	FirstSeen   int64
}

type Project struct {
	ID        int64
	Name      string
	CompanyID sql.NullInt64
	Paused    int64
	CreatedAt int64
}

type Rule struct {
	ID               int64
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
	CreatedAt        int64
}

type SenderState struct {
	SenderKey         string
	NextInvoiceNumber int64
}

type Tick struct {
	Ts            int64
	ObservationID int64
	ProjectID     sql.NullInt64
}

type WatchedProgram struct {
	ID         int64
	Kind       string
	Identifier string
	CreatedAt  int64
}
