// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addProject = `-- name: AddProject :one
INSERT INTO projects (name, created_at) VALUES (?, ?) RETURNING id
`

type AddProjectParams struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) AddProject(ctx context.Context, arg AddProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addProject, arg.Name, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addRule = `-- name: AddRule :one
INSERT INTO rules (project_id, priority, match_bundle_id, match_title_substr, match_binary_name, match_cwd_prefix, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type AddRuleParams struct {
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
	CreatedAt        int64
}

func (q *Queries) AddRule(ctx context.Context, arg AddRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addRule,
		arg.ProjectID,
		arg.Priority,
		arg.MatchBundleID,
		arg.MatchTitleSubstr,
		arg.MatchBinaryName,
		arg.MatchCwdPrefix,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addWatchedProgram = `-- name: AddWatchedProgram :exec
INSERT INTO watched_programs (kind, identifier, created_at) VALUES (?, ?, ?)
`

type AddWatchedProgramParams struct {
	Kind       string
	Identifier string
	CreatedAt  int64
}

func (q *Queries) AddWatchedProgram(ctx context.Context, arg AddWatchedProgramParams) error {
	_, err := q.db.ExecContext(ctx, addWatchedProgram, arg.Kind, arg.Identifier, arg.CreatedAt)
	return err
}

const countPendingReviewSignatures = `-- name: CountPendingReviewSignatures :one
SELECT COUNT(DISTINCT o.id) AS n
FROM observations o
JOIN ticks t ON t.observation_id = o.id
WHERE t.project_id IS NULL
  AND o.id NOT IN (SELECT observation_id FROM ignored_observations)
`

func (q *Queries) CountPendingReviewSignatures(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingReviewSignatures)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteProjectByName = `-- name: DeleteProjectByName :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProjectByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectByName, name)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getObservation = `-- name: GetObservation :one
SELECT id, source, bundle_id, window_title, binary_name, cwd, first_seen
FROM observations
WHERE id = ?
`

func (q *Queries) GetObservation(ctx context.Context, id int64) (Observation, error) {
	row := q.db.QueryRowContext(ctx, getObservation, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.BundleID,
		&i.WindowTitle,
		&i.BinaryName,
		&i.Cwd,
		&i.FirstSeen,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name FROM projects WHERE name = ?
`

type GetProjectByNameRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetProjectByName(ctx context.Context, name string) (GetProjectByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i GetProjectByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const ignoreObservation = `-- name: IgnoreObservation :exec
INSERT INTO ignored_observations (observation_id, ignored_at)
VALUES (?, ?)
ON CONFLICT (observation_id) DO NOTHING
`

type IgnoreObservationParams struct {
	ObservationID int64
	IgnoredAt     int64
}

func (q *Queries) IgnoreObservation(ctx context.Context, arg IgnoreObservationParams) error {
	_, err := q.db.ExecContext(ctx, ignoreObservation, arg.ObservationID, arg.IgnoredAt)
	return err
}

const insertTick = `-- name: InsertTick :exec
INSERT OR IGNORE INTO ticks (ts, observation_id, project_id) VALUES (?, ?, ?)
`

type InsertTickParams struct {
	Ts            int64
	ObservationID int64
	ProjectID     sql.NullInt64
}

func (q *Queries) InsertTick(ctx context.Context, arg InsertTickParams) error {
	_, err := q.db.ExecContext(ctx, insertTick, arg.Ts, arg.ObservationID, arg.ProjectID)
	return err
}

const isObservationIgnored = `-- name: IsObservationIgnored :one
SELECT EXISTS(SELECT 1 FROM ignored_observations WHERE observation_id = ?) AS ignored
`

func (q *Queries) IsObservationIgnored(ctx context.Context, observationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isObservationIgnored, observationID)
	var ignored int64
	err := row.Scan(&ignored)
	return ignored, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name FROM projects ORDER BY name
`

type ListProjectsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT r.id, p.name AS project_name, r.priority,
       r.match_bundle_id, r.match_title_substr, r.match_binary_name, r.match_cwd_prefix
FROM rules r
JOIN projects p ON p.id = r.project_id
ORDER BY r.priority, r.id
`

type ListRulesRow struct {
	ID               int64
	ProjectName      string
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
}

func (q *Queries) ListRules(ctx context.Context) ([]ListRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesRow{}
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Priority,
			&i.MatchBundleID,
			&i.MatchTitleSubstr,
			&i.MatchBinaryName,
			&i.MatchCwdPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForCache = `-- name: ListRulesForCache :many
SELECT id, project_id, priority,
       match_bundle_id, match_title_substr, match_binary_name, match_cwd_prefix
FROM rules
ORDER BY priority, id
`

type ListRulesForCacheRow struct {
	ID               int64
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
}

func (q *Queries) ListRulesForCache(ctx context.Context) ([]ListRulesForCacheRow, error) {
	rows, err := q.db.QueryContext(ctx, listRulesForCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesForCacheRow{}
	for rows.Next() {
		var i ListRulesForCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Priority,
			&i.MatchBundleID,
			&i.MatchTitleSubstr,
			&i.MatchBinaryName,
			&i.MatchCwdPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedPrograms = `-- name: ListWatchedPrograms :many
SELECT id, kind, identifier FROM watched_programs ORDER BY kind, identifier
`

type ListWatchedProgramsRow struct {
	ID         int64
	Kind       string
	Identifier string
}

func (q *Queries) ListWatchedPrograms(ctx context.Context) ([]ListWatchedProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchedProgramsRow{}
	for rows.Next() {
		var i ListWatchedProgramsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingReviewSignatures = `-- name: PendingReviewSignatures :many
SELECT o.id, o.source, o.bundle_id, o.window_title, o.binary_name, o.cwd,
       COUNT(t.ts) AS ticks, MAX(t.ts) AS last_seen
FROM observations o
JOIN ticks t ON t.observation_id = o.id
WHERE t.project_id IS NULL
  AND o.id NOT IN (SELECT observation_id FROM ignored_observations)
GROUP BY o.id
ORDER BY ticks DESC
LIMIT ?
`

type PendingReviewSignaturesRow struct {
	ID          int64
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	Ticks       int64
	LastSeen    interface{}
}

func (q *Queries) PendingReviewSignatures(ctx context.Context, limit int64) ([]PendingReviewSignaturesRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingReviewSignatures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingReviewSignaturesRow{}
	for rows.Next() {
		var i PendingReviewSignaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.BundleID,
			&i.WindowTitle,
			&i.BinaryName,
			&i.Cwd,
			&i.Ticks,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWatchedProgram = `-- name: RemoveWatchedProgram :exec
DELETE FROM watched_programs WHERE kind = ? AND identifier = ?
`

type RemoveWatchedProgramParams struct {
	Kind       string
	Identifier string
}

func (q *Queries) RemoveWatchedProgram(ctx context.Context, arg RemoveWatchedProgramParams) error {
	_, err := q.db.ExecContext(ctx, removeWatchedProgram, arg.Kind, arg.Identifier)
	return err
}

const totalsByProject = `-- name: TotalsByProject :many
SELECT p.name, COUNT(DISTINCT t.ts) AS tick_count
FROM ticks t
JOIN projects p ON p.id = t.project_id
WHERE t.ts >= ? AND t.ts < ?
GROUP BY p.id
`

type TotalsByProjectParams struct {
	Ts   int64
	Ts_2 int64
}

type TotalsByProjectRow struct {
	Name      string
	TickCount int64
}

func (q *Queries) TotalsByProject(ctx context.Context, arg TotalsByProjectParams) ([]TotalsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, totalsByProject, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalsByProjectRow{}
	for rows.Next() {
		var i TotalsByProjectRow
		if err := rows.Scan(&i.Name, &i.TickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignedTicksInRange = `-- name: UnassignedTicksInRange :one
SELECT COUNT(DISTINCT ts) AS tick_count
FROM ticks
WHERE project_id IS NULL AND ts >= ? AND ts < ?
`

type UnassignedTicksInRangeParams struct {
	Ts   int64
	Ts_2 int64
}

func (q *Queries) UnassignedTicksInRange(ctx context.Context, arg UnassignedTicksInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, unassignedTicksInRange, arg.Ts, arg.Ts_2)
	var tick_count int64
	err := row.Scan(&tick_count)
	return tick_count, err
}

const upsertObservation = `-- name: UpsertObservation :one
INSERT INTO observations (source, bundle_id, window_title, binary_name, cwd, first_seen)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (source, bundle_id, window_title, binary_name, cwd)
DO UPDATE SET id = id
RETURNING id
`

type UpsertObservationParams struct {
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	FirstSeen   int64
}

func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertObservation,
		arg.Source,
		arg.BundleID,
		arg.WindowTitle,
		arg.BinaryName,
		arg.Cwd,
		arg.FirstSeen,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
