// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addCompany = `-- name: AddCompany :one
INSERT INTO companies (name, created_at) VALUES (?, ?) RETURNING id
`

type AddCompanyParams struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) AddCompany(ctx context.Context, arg AddCompanyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addCompany, arg.Name, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addInvoice = `-- name: AddInvoice :one
INSERT INTO invoices (company_id, sent_at, note, created_at) VALUES (?, ?, ?, ?) RETURNING id
`

type AddInvoiceParams struct {
	CompanyID int64
	SentAt    int64
	Note      string
	CreatedAt int64
}

func (q *Queries) AddInvoice(ctx context.Context, arg AddInvoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addInvoice,
		arg.CompanyID,
		arg.SentAt,
		arg.Note,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addProject = `-- name: AddProject :one
INSERT INTO projects (name, company_id, created_at) VALUES (?, ?, ?) RETURNING id
`

type AddProjectParams struct {
	Name      string
	CompanyID sql.NullInt64
	CreatedAt int64
}

func (q *Queries) AddProject(ctx context.Context, arg AddProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addProject, arg.Name, arg.CompanyID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addRule = `-- name: AddRule :one
INSERT INTO rules (project_id, priority, match_bundle_id, match_title_substr, match_binary_name, match_cwd_prefix, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type AddRuleParams struct {
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
	CreatedAt        int64
}

func (q *Queries) AddRule(ctx context.Context, arg AddRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addRule,
		arg.ProjectID,
		arg.Priority,
		arg.MatchBundleID,
		arg.MatchTitleSubstr,
		arg.MatchBinaryName,
		arg.MatchCwdPrefix,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addWatchedProgram = `-- name: AddWatchedProgram :exec
INSERT INTO watched_programs (kind, identifier, created_at) VALUES (?, ?, ?)
`

type AddWatchedProgramParams struct {
	Kind       string
	Identifier string
	CreatedAt  int64
}

func (q *Queries) AddWatchedProgram(ctx context.Context, arg AddWatchedProgramParams) error {
	_, err := q.db.ExecContext(ctx, addWatchedProgram, arg.Kind, arg.Identifier, arg.CreatedAt)
	return err
}

const allocateNextInvoiceNumber = `-- name: AllocateNextInvoiceNumber :one
UPDATE sender_state
SET next_invoice_number = next_invoice_number + 1
WHERE sender_key = ?
RETURNING next_invoice_number - 1 AS allocated
`

func (q *Queries) AllocateNextInvoiceNumber(ctx context.Context, senderKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocateNextInvoiceNumber, senderKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const applyRuleRetroactivelyCounted = `-- name: ApplyRuleRetroactivelyCounted :execrows
UPDATE ticks
SET project_id = ?
WHERE project_id IS NULL
  AND observation_id IN (
      SELECT id FROM observations
      WHERE (? IS NULL OR bundle_id = ?)
        AND (? IS NULL OR window_title LIKE '%' || ? || '%')
        AND (? IS NULL OR binary_name = ?)
        AND (? IS NULL OR cwd LIKE ? || '%')
  )
`

type ApplyRuleRetroactivelyCountedParams struct {
	ProjectID  sql.NullInt64
	Column2    interface{}
	BundleID   string
	Column4    interface{}
	Column5    sql.NullString
	Column6    interface{}
	BinaryName string
	Column8    interface{}
	Column9    sql.NullString
}

func (q *Queries) ApplyRuleRetroactivelyCounted(ctx context.Context, arg ApplyRuleRetroactivelyCountedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyRuleRetroactivelyCounted,
		arg.ProjectID,
		arg.Column2,
		arg.BundleID,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.BinaryName,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const assignedDistinctTicksInRange = `-- name: AssignedDistinctTicksInRange :one
SELECT COUNT(DISTINCT ts) AS tick_count
FROM ticks
WHERE project_id IS NOT NULL AND ts >= ? AND ts < ?
`

type AssignedDistinctTicksInRangeParams struct {
	Ts   int64
	Ts_2 int64
}

// COUNT(DISTINCT ts) of project-assigned ticks in a half-open range.
// Used by Status to compute today's total without double-counting
// timestamps that have ticks for multiple projects (the sum-of-per-project
// counts overcounts those collisions).
func (q *Queries) AssignedDistinctTicksInRange(ctx context.Context, arg AssignedDistinctTicksInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, assignedDistinctTicksInRange, arg.Ts, arg.Ts_2)
	var tick_count int64
	err := row.Scan(&tick_count)
	return tick_count, err
}

const companyCreditBalance = `-- name: CompanyCreditBalance :one
SELECT COALESCE(SUM(CASE WHEN kind = 'advance' THEN total_cents ELSE 0 END), 0)
     - COALESCE(SUM(credit_applied_cents), 0) AS remaining_cents
FROM invoices
WHERE company_id = ? AND currency = ?
`

type CompanyCreditBalanceParams struct {
	CompanyID int64
	Currency  sql.NullString
}

// Remaining prepaid credit for a company in one currency: total advanced
// minus total drawn down. discount_cents (goodwill) never enters this sum.
func (q *Queries) CompanyCreditBalance(ctx context.Context, arg CompanyCreditBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, companyCreditBalance, arg.CompanyID, arg.Currency)
	var remaining_cents int64
	err := row.Scan(&remaining_cents)
	return remaining_cents, err
}

const companyCreditRows = `-- name: CompanyCreditRows :many
SELECT number, kind, total_cents, credit_applied_cents, sent_at
FROM invoices
WHERE company_id = ? AND currency = ?
  AND (kind = 'advance' OR credit_applied_cents > 0)
ORDER BY sent_at DESC, id DESC
`

type CompanyCreditRowsParams struct {
	CompanyID int64
	Currency  sql.NullString
}

type CompanyCreditRowsRow struct {
	Number             sql.NullString
	Kind               string
	TotalCents         sql.NullInt64
	CreditAppliedCents int64
	SentAt             int64
}

// Rows that make up a company's credit ledger in one currency: advances
// (credits) and any invoice that drew down credit (debits).
func (q *Queries) CompanyCreditRows(ctx context.Context, arg CompanyCreditRowsParams) ([]CompanyCreditRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, companyCreditRows, arg.CompanyID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanyCreditRowsRow{}
	for rows.Next() {
		var i CompanyCreditRowsRow
		if err := rows.Scan(
			&i.Number,
			&i.Kind,
			&i.TotalCents,
			&i.CreditAppliedCents,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDistinctCompanyTicksSince = `-- name: CountDistinctCompanyTicksSince :one
SELECT COUNT(DISTINCT t.ts) AS tick_count
FROM ticks t
JOIN projects p ON p.id = t.project_id
WHERE p.company_id IS ? AND t.ts >= ?
`

type CountDistinctCompanyTicksSinceParams struct {
	CompanyID sql.NullInt64
	Ts        int64
}

// Company-level billable seconds (as distinct ts) since a cutoff, for the
// Status rollup. `company_id IS ?` is null-safe, so passing NULL counts the
// "(no company)" bucket. No paused filter: pause stops NEW ticks at write
// time, so historical ticks here are real work (see commit 9b6359b).
func (q *Queries) CountDistinctCompanyTicksSince(ctx context.Context, arg CountDistinctCompanyTicksSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctCompanyTicksSince, arg.CompanyID, arg.Ts)
	var tick_count int64
	err := row.Scan(&tick_count)
	return tick_count, err
}

const countInvoicesByCompanyID = `-- name: CountInvoicesByCompanyID :one
SELECT COUNT(*) AS invoice_count FROM invoices WHERE company_id = ?
`

// Used by the CompanyDelete guard: invoices.company_id is ON DELETE CASCADE,
// so an unguarded delete of a company with any invoices would silently
// vaporise advance credit along with the row history.
func (q *Queries) CountInvoicesByCompanyID(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoicesByCompanyID, companyID)
	var invoice_count int64
	err := row.Scan(&invoice_count)
	return invoice_count, err
}

const countPendingReviewSignatures = `-- name: CountPendingReviewSignatures :one
SELECT COUNT(DISTINCT o.id) AS n
FROM observations o
JOIN ticks t ON t.observation_id = o.id
WHERE t.project_id IS NULL
  AND o.id NOT IN (SELECT observation_id FROM ignored_observations)
`

func (q *Queries) CountPendingReviewSignatures(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingReviewSignatures)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countTicksForCompanyInRange = `-- name: CountTicksForCompanyInRange :one
SELECT COUNT(DISTINCT t.ts) FROM ticks t
JOIN projects p ON p.id = t.project_id
WHERE p.company_id = ? AND p.paused = 0
  AND t.ts >= ? AND t.ts < ?
`

type CountTicksForCompanyInRangeParams struct {
	CompanyID sql.NullInt64
	Ts        int64
	Ts_2      int64
}

// COUNT(DISTINCT ts) so a second worked across multiple projects of the same
// company (or multiple windows of one project) bills once, not once per row.
func (q *Queries) CountTicksForCompanyInRange(ctx context.Context, arg CountTicksForCompanyInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicksForCompanyInRange, arg.CompanyID, arg.Ts, arg.Ts_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCompanyByName = `-- name: DeleteCompanyByName :exec
DELETE FROM companies WHERE name = ?
`

func (q *Queries) DeleteCompanyByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCompanyByName, name)
	return err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const deleteProjectByName = `-- name: DeleteProjectByName :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProjectByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectByName, name)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getCompanyByName = `-- name: GetCompanyByName :one
SELECT id, name FROM companies WHERE name = ?
`

type GetCompanyByNameRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetCompanyByName(ctx context.Context, name string) (GetCompanyByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByName, name)
	var i GetCompanyByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCompanyForInvoice = `-- name: GetCompanyForInvoice :one
SELECT id, name, created_at, billing_mode, currency, rate_cents, billed_from
FROM companies WHERE name = ?
`

func (q *Queries) GetCompanyForInvoice(ctx context.Context, name string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyForInvoice, name)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BillingMode,
		&i.Currency,
		&i.RateCents,
		&i.BilledFrom,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, company_id, sent_at, note, created_at, number, pdf_path,
       total_cents, currency, sender_key, kind, credit_applied_cents, discount_cents
FROM invoices WHERE id = ?
`

// Used by the InvoiceDelete guard: an invoice that is kind='advance' or has
// drawn down credit (credit_applied_cents > 0) must not be deleted without
// --force, since the balance is derived from these rows and the client's PDF
// already reflects the credit as consumed.
func (q *Queries) GetInvoiceByID(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SentAt,
		&i.Note,
		&i.CreatedAt,
		&i.Number,
		&i.PdfPath,
		&i.TotalCents,
		&i.Currency,
		&i.SenderKey,
		&i.Kind,
		&i.CreditAppliedCents,
		&i.DiscountCents,
	)
	return i, err
}

const getObservation = `-- name: GetObservation :one
SELECT id, source, bundle_id, window_title, binary_name, cwd, first_seen
FROM observations
WHERE id = ?
`

func (q *Queries) GetObservation(ctx context.Context, id int64) (Observation, error) {
	row := q.db.QueryRowContext(ctx, getObservation, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.BundleID,
		&i.WindowTitle,
		&i.BinaryName,
		&i.Cwd,
		&i.FirstSeen,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name FROM projects WHERE name = ?
`

type GetProjectByNameRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetProjectByName(ctx context.Context, name string) (GetProjectByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i GetProjectByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const ignoreObservation = `-- name: IgnoreObservation :exec
INSERT INTO ignored_observations (observation_id, ignored_at)
VALUES (?, ?)
ON CONFLICT (observation_id) DO NOTHING
`

type IgnoreObservationParams struct {
	ObservationID int64
	IgnoredAt     int64
}

func (q *Queries) IgnoreObservation(ctx context.Context, arg IgnoreObservationParams) error {
	_, err := q.db.ExecContext(ctx, ignoreObservation, arg.ObservationID, arg.IgnoredAt)
	return err
}

const insertInvoiceFull = `-- name: InsertInvoiceFull :one
INSERT INTO invoices (
    company_id, sent_at, note, created_at,
    number, pdf_path, total_cents, currency, sender_key,
    kind, credit_applied_cents, discount_cents
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertInvoiceFullParams struct {
	CompanyID          int64
	SentAt             int64
	Note               string
	CreatedAt          int64
	Number             sql.NullString
	PdfPath            sql.NullString
	TotalCents         sql.NullInt64
	Currency           sql.NullString
	SenderKey          sql.NullString
	Kind               string
	CreditAppliedCents int64
	DiscountCents      int64
}

func (q *Queries) InsertInvoiceFull(ctx context.Context, arg InsertInvoiceFullParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertInvoiceFull,
		arg.CompanyID,
		arg.SentAt,
		arg.Note,
		arg.CreatedAt,
		arg.Number,
		arg.PdfPath,
		arg.TotalCents,
		arg.Currency,
		arg.SenderKey,
		arg.Kind,
		arg.CreditAppliedCents,
		arg.DiscountCents,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTick = `-- name: InsertTick :exec
INSERT OR IGNORE INTO ticks (ts, observation_id, project_id) VALUES (?, ?, ?)
`

type InsertTickParams struct {
	Ts            int64
	ObservationID int64
	ProjectID     sql.NullInt64
}

func (q *Queries) InsertTick(ctx context.Context, arg InsertTickParams) error {
	_, err := q.db.ExecContext(ctx, insertTick, arg.Ts, arg.ObservationID, arg.ProjectID)
	return err
}

const isObservationIgnored = `-- name: IsObservationIgnored :one
SELECT EXISTS(SELECT 1 FROM ignored_observations WHERE observation_id = ?) AS ignored
`

func (q *Queries) IsObservationIgnored(ctx context.Context, observationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isObservationIgnored, observationID)
	var ignored int64
	err := row.Scan(&ignored)
	return ignored, err
}

const lastInvoicePerCompany = `-- name: LastInvoicePerCompany :many
SELECT company_id, MAX(sent_at) AS last_sent
FROM invoices GROUP BY company_id
`

type LastInvoicePerCompanyRow struct {
	CompanyID int64
	LastSent  interface{}
}

func (q *Queries) LastInvoicePerCompany(ctx context.Context) ([]LastInvoicePerCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, lastInvoicePerCompany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastInvoicePerCompanyRow{}
	for rows.Next() {
		var i LastInvoicePerCompanyRow
		if err := rows.Scan(&i.CompanyID, &i.LastSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastInvoiceSentForCompany = `-- name: LastInvoiceSentForCompany :one
SELECT sent_at FROM invoices
WHERE company_id = ? AND kind <> 'advance'
ORDER BY sent_at DESC, id DESC LIMIT 1
`

// Advance invoices close no billing period, so they must not move the
// anchor: an hour worked between the last real invoice and an advance
// would otherwise be silently dropped from every future invoice.
func (q *Queries) LastInvoiceSentForCompany(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastInvoiceSentForCompany, companyID)
	var sent_at int64
	err := row.Scan(&sent_at)
	return sent_at, err
}

const listAllInvoices = `-- name: ListAllInvoices :many
SELECT i.id, c.name AS company_name, i.sent_at, i.note,
       i.number, i.kind, i.total_cents, i.credit_applied_cents, i.currency
FROM invoices i
JOIN companies c ON c.id = i.company_id
ORDER BY i.sent_at DESC, i.id DESC
`

type ListAllInvoicesRow struct {
	ID                 int64
	CompanyName        string
	SentAt             int64
	Note               string
	Number             sql.NullString
	Kind               string
	TotalCents         sql.NullInt64
	CreditAppliedCents int64
	Currency           sql.NullString
}

func (q *Queries) ListAllInvoices(ctx context.Context) ([]ListAllInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInvoicesRow{}
	for rows.Next() {
		var i ListAllInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.SentAt,
			&i.Note,
			&i.Number,
			&i.Kind,
			&i.TotalCents,
			&i.CreditAppliedCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name FROM companies ORDER BY name
`

type ListCompaniesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByCompany = `-- name: ListInvoicesByCompany :many
SELECT i.id, c.name AS company_name, i.sent_at, i.note,
       i.number, i.kind, i.total_cents, i.credit_applied_cents, i.currency
FROM invoices i
JOIN companies c ON c.id = i.company_id
WHERE i.company_id = ?
ORDER BY i.sent_at DESC, i.id DESC
`

type ListInvoicesByCompanyRow struct {
	ID                 int64
	CompanyName        string
	SentAt             int64
	Note               string
	Number             sql.NullString
	Kind               string
	TotalCents         sql.NullInt64
	CreditAppliedCents int64
	Currency           sql.NullString
}

func (q *Queries) ListInvoicesByCompany(ctx context.Context, companyID int64) ([]ListInvoicesByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesByCompanyRow{}
	for rows.Next() {
		var i ListInvoicesByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.SentAt,
			&i.Note,
			&i.Number,
			&i.Kind,
			&i.TotalCents,
			&i.CreditAppliedCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPausedProjectIDs = `-- name: ListPausedProjectIDs :many
SELECT id FROM projects WHERE paused = 1
`

func (q *Queries) ListPausedProjectIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPausedProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.name, p.paused, c.name AS company_name
FROM projects p
LEFT JOIN companies c ON c.id = p.company_id
ORDER BY p.name
`

type ListProjectsRow struct {
	ID          int64
	Name        string
	Paused      int64
	CompanyName sql.NullString
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Paused,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithCompany = `-- name: ListProjectsWithCompany :many
SELECT p.id, p.name, p.company_id, p.paused, c.name AS company_name
FROM projects p
LEFT JOIN companies c ON c.id = p.company_id
ORDER BY c.name, p.name
`

type ListProjectsWithCompanyRow struct {
	ID          int64
	Name        string
	CompanyID   sql.NullInt64
	Paused      int64
	CompanyName sql.NullString
}

func (q *Queries) ListProjectsWithCompany(ctx context.Context) ([]ListProjectsWithCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsWithCompany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsWithCompanyRow{}
	for rows.Next() {
		var i ListProjectsWithCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompanyID,
			&i.Paused,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT r.id, p.name AS project_name, r.priority,
       r.match_bundle_id, r.match_title_substr, r.match_binary_name, r.match_cwd_prefix
FROM rules r
JOIN projects p ON p.id = r.project_id
ORDER BY r.priority, r.id
`

type ListRulesRow struct {
	ID               int64
	ProjectName      string
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
}

func (q *Queries) ListRules(ctx context.Context) ([]ListRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesRow{}
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Priority,
			&i.MatchBundleID,
			&i.MatchTitleSubstr,
			&i.MatchBinaryName,
			&i.MatchCwdPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForCache = `-- name: ListRulesForCache :many
SELECT id, project_id, priority,
       match_bundle_id, match_title_substr, match_binary_name, match_cwd_prefix
FROM rules
ORDER BY priority, id
`

type ListRulesForCacheRow struct {
	ID               int64
	ProjectID        int64
	Priority         int64
	MatchBundleID    sql.NullString
	MatchTitleSubstr sql.NullString
	MatchBinaryName  sql.NullString
	MatchCwdPrefix   sql.NullString
}

func (q *Queries) ListRulesForCache(ctx context.Context) ([]ListRulesForCacheRow, error) {
	rows, err := q.db.QueryContext(ctx, listRulesForCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesForCacheRow{}
	for rows.Next() {
		var i ListRulesForCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Priority,
			&i.MatchBundleID,
			&i.MatchTitleSubstr,
			&i.MatchBinaryName,
			&i.MatchCwdPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedPrograms = `-- name: ListWatchedPrograms :many
SELECT id, kind, identifier FROM watched_programs ORDER BY kind, identifier
`

type ListWatchedProgramsRow struct {
	ID         int64
	Kind       string
	Identifier string
}

func (q *Queries) ListWatchedPrograms(ctx context.Context) ([]ListWatchedProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchedProgramsRow{}
	for rows.Next() {
		var i ListWatchedProgramsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTickTs = `-- name: MaxTickTs :one
SELECT CAST(COALESCE(MAX(ts), 0) AS INTEGER) AS max_ts FROM ticks
`

// Cheap "has anything changed?" probe for the live status view: the newest
// tick timestamp (0 when there are no ticks). Indexed, ~instant.
func (q *Queries) MaxTickTs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTickTs)
	var max_ts int64
	err := row.Scan(&max_ts)
	return max_ts, err
}

const pauseAllProjects = `-- name: PauseAllProjects :execrows
UPDATE projects SET paused = 1
`

func (q *Queries) PauseAllProjects(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, pauseAllProjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pendingReviewSignatures = `-- name: PendingReviewSignatures :many
SELECT o.id, o.source, o.bundle_id, o.window_title, o.binary_name, o.cwd,
       COUNT(t.ts) AS ticks, COALESCE(MAX(t.ts), 0) AS last_seen
FROM observations o
JOIN ticks t ON t.observation_id = o.id
WHERE t.project_id IS NULL
  AND o.id NOT IN (SELECT observation_id FROM ignored_observations)
GROUP BY o.id
ORDER BY ticks DESC
LIMIT ?
`

type PendingReviewSignaturesRow struct {
	ID          int64
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	Ticks       int64
	LastSeen    interface{}
}

func (q *Queries) PendingReviewSignatures(ctx context.Context, limit int64) ([]PendingReviewSignaturesRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingReviewSignatures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingReviewSignaturesRow{}
	for rows.Next() {
		var i PendingReviewSignaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.BundleID,
			&i.WindowTitle,
			&i.BinaryName,
			&i.Cwd,
			&i.Ticks,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWatchedProgram = `-- name: RemoveWatchedProgram :exec
DELETE FROM watched_programs WHERE kind = ? AND identifier = ?
`

type RemoveWatchedProgramParams struct {
	Kind       string
	Identifier string
}

func (q *Queries) RemoveWatchedProgram(ctx context.Context, arg RemoveWatchedProgramParams) error {
	_, err := q.db.ExecContext(ctx, removeWatchedProgram, arg.Kind, arg.Identifier)
	return err
}

const resumeAllProjects = `-- name: ResumeAllProjects :execrows
UPDATE projects SET paused = 0
`

func (q *Queries) ResumeAllProjects(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumeAllProjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resumeProjectByID = `-- name: ResumeProjectByID :exec
UPDATE projects SET paused = 0 WHERE id = ?
`

func (q *Queries) ResumeProjectByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resumeProjectByID, id)
	return err
}

const retagSingleObservation = `-- name: RetagSingleObservation :exec
UPDATE ticks
SET project_id = ?
WHERE project_id IS NULL AND observation_id = ?
`

type RetagSingleObservationParams struct {
	ProjectID     sql.NullInt64
	ObservationID int64
}

func (q *Queries) RetagSingleObservation(ctx context.Context, arg RetagSingleObservationParams) error {
	_, err := q.db.ExecContext(ctx, retagSingleObservation, arg.ProjectID, arg.ObservationID)
	return err
}

const seedSenderState = `-- name: SeedSenderState :exec
INSERT OR IGNORE INTO sender_state (sender_key, next_invoice_number) VALUES (?, ?)
`

type SeedSenderStateParams struct {
	SenderKey         string
	NextInvoiceNumber int64
}

func (q *Queries) SeedSenderState(ctx context.Context, arg SeedSenderStateParams) error {
	_, err := q.db.ExecContext(ctx, seedSenderState, arg.SenderKey, arg.NextInvoiceNumber)
	return err
}

const setCompanyBilling = `-- name: SetCompanyBilling :exec
UPDATE companies
SET billing_mode = ?, currency = ?, rate_cents = ?, billed_from = ?
WHERE name = ?
`

type SetCompanyBillingParams struct {
	BillingMode string
	Currency    sql.NullString
	RateCents   sql.NullInt64
	BilledFrom  sql.NullString
	Name        string
}

func (q *Queries) SetCompanyBilling(ctx context.Context, arg SetCompanyBillingParams) error {
	_, err := q.db.ExecContext(ctx, setCompanyBilling,
		arg.BillingMode,
		arg.Currency,
		arg.RateCents,
		arg.BilledFrom,
		arg.Name,
	)
	return err
}

const setProjectCompany = `-- name: SetProjectCompany :exec
UPDATE projects SET company_id = ? WHERE name = ?
`

type SetProjectCompanyParams struct {
	CompanyID sql.NullInt64
	Name      string
}

func (q *Queries) SetProjectCompany(ctx context.Context, arg SetProjectCompanyParams) error {
	_, err := q.db.ExecContext(ctx, setProjectCompany, arg.CompanyID, arg.Name)
	return err
}

const setProjectPaused = `-- name: SetProjectPaused :exec
UPDATE projects SET paused = ? WHERE name = ?
`

type SetProjectPausedParams struct {
	Paused int64
	Name   string
}

func (q *Queries) SetProjectPaused(ctx context.Context, arg SetProjectPausedParams) error {
	_, err := q.db.ExecContext(ctx, setProjectPaused, arg.Paused, arg.Name)
	return err
}

const totalsByProject = `-- name: TotalsByProject :many
SELECT p.name, COUNT(DISTINCT t.ts) AS tick_count
FROM ticks t
JOIN projects p ON p.id = t.project_id
WHERE t.ts >= ? AND t.ts < ?
GROUP BY p.id
`

type TotalsByProjectParams struct {
	Ts   int64
	Ts_2 int64
}

type TotalsByProjectRow struct {
	Name      string
	TickCount int64
}

func (q *Queries) TotalsByProject(ctx context.Context, arg TotalsByProjectParams) ([]TotalsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, totalsByProject, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalsByProjectRow{}
	for rows.Next() {
		var i TotalsByProjectRow
		if err := rows.Scan(&i.Name, &i.TickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalsByProjectSince = `-- name: TotalsByProjectSince :many
SELECT p.id AS project_id, p.name, COUNT(DISTINCT t.ts) AS tick_count
FROM ticks t
JOIN projects p ON p.id = t.project_id
WHERE t.ts >= ?
GROUP BY p.id
`

type TotalsByProjectSinceRow struct {
	ProjectID int64
	Name      string
	TickCount int64
}

func (q *Queries) TotalsByProjectSince(ctx context.Context, ts int64) ([]TotalsByProjectSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, totalsByProjectSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalsByProjectSinceRow{}
	for rows.Next() {
		var i TotalsByProjectSinceRow
		if err := rows.Scan(&i.ProjectID, &i.Name, &i.TickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignedTicksAllTime = `-- name: UnassignedTicksAllTime :one
SELECT COUNT(DISTINCT ts) AS tick_count FROM ticks WHERE project_id IS NULL
`

func (q *Queries) UnassignedTicksAllTime(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, unassignedTicksAllTime)
	var tick_count int64
	err := row.Scan(&tick_count)
	return tick_count, err
}

const unassignedTicksInRange = `-- name: UnassignedTicksInRange :one
SELECT COUNT(DISTINCT ts) AS tick_count
FROM ticks
WHERE project_id IS NULL AND ts >= ? AND ts < ?
`

type UnassignedTicksInRangeParams struct {
	Ts   int64
	Ts_2 int64
}

func (q *Queries) UnassignedTicksInRange(ctx context.Context, arg UnassignedTicksInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, unassignedTicksInRange, arg.Ts, arg.Ts_2)
	var tick_count int64
	err := row.Scan(&tick_count)
	return tick_count, err
}

const upsertObservation = `-- name: UpsertObservation :one
INSERT INTO observations (source, bundle_id, window_title, binary_name, cwd, first_seen)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (source, bundle_id, window_title, binary_name, cwd)
DO UPDATE SET id = id
RETURNING id
`

type UpsertObservationParams struct {
	Source      string
	BundleID    string
	WindowTitle string
	BinaryName  string
	Cwd         string
	FirstSeen   int64
}

func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertObservation,
		arg.Source,
		arg.BundleID,
		arg.WindowTitle,
		arg.BinaryName,
		arg.Cwd,
		arg.FirstSeen,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
